# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FGEPmC2m7RFna_4y7wfoYPfnKXgwl2g1
"""

print("Welcome to CS213 by Ayesha Muqeem")